version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - |
        set -e
        echo "Logging in to ECR Public... new with new entry point in dockerfile"
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

        echo "Building Docker image..."
        docker build -t kirana-image:latest -f Dockerfile .

        echo "Verifying JAR inside image..."
        docker run --rm --entrypoint ls kirana-image:latest -la /app/

        echo "Image built and verified successfully"

  build:
    commands:
      - |
        set -e
        export ECR_URI="505038841552.dkr.ecr.us-west-2.amazonaws.com/kirana-be"
        echo "ECR_URI: ${ECR_URI}"

        echo "Logging in to ECR..."
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $ECR_URI

        IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
        echo "Tagging image: latest and ${IMAGE_TAG}"
        docker tag kirana-image:latest $ECR_URI:latest
        docker tag kirana-image:latest $ECR_URI:$IMAGE_TAG

        echo "Pushing images..."
        docker push $ECR_URI:latest
        docker push $ECR_URI:$IMAGE_TAG
        echo "Push completed successfully"
